import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt
import scipy.integrate as integrate
from Project_utils import *
import warnings
warnings.simplefilter("ignore")
np.random.seed(12)

K = 4
N = 10000
p = [lambda loc: st.norm.rvs(loc=loc, scale=3)] * K
gammas = [1, 2, 4, 8, 16]
a = 2
u0 = st.uniform(loc=-3, scale=6).rvs
Ns = 1
x = np.zeros((K, N))
x_walk = np.zeros((N,))
x_t = np.linspace(-5, 5, 1000)
# plot the histograms of samples
fig = plt.figure(figsize=(25, 10))
for j, gamma in enumerate(gammas):
    u = [lambda x, i=i: np.exp(-gamma * (x ** 2 - 1) ** 2 / (a ** i)) for i in range(K)]
    xs, acc = simple_parallel_tempering(x, K, N, p, u, u0, Ns)
    xs_walk = random_walk_metropolis(x_walk, N, p[0], u[0], u0)
    stat = {'acceptance rate': acc}
    print('acceptance rate when gamma=%d: %f' % (gamma, stat['acceptance rate']))
    y_t = u[0](x_t)
    integral = integrate.quad(u[0], -5, 5)[0]

    ax = fig.add_subplot(2, 5, j + 1)
    ax.hist(xs, bins=100, density=True, label='simple_PT')
    ax.plot(x_t, y_t / integral, linewidth=1.5, label=r'$\tilde{f}(x)$')
    ax.set_title('gamma = ' + str(gamma))
    plt.legend()

    ax2 = fig.add_subplot(2, 5, 5+ j + 1)
    ax2.hist(xs_walk, bins=100, density=True, label='Walk')
    ax2.plot(x_t, y_t / integral, linewidth=1.5, label=r'$\tilde{f}(x)$')
    ax2.set_title('gamma = ' + str(gamma))
    plt.legend()
plt.savefig('figures/project_ex2_hist.png')
plt.show()

# plot the auto-correlation plots
x = np.zeros((K, N))
fig = plt.figure(figsize=(20, 20))
for j, gamma in enumerate(gammas):
    u = [lambda x, i=i: np.exp(-gamma * (x ** 2 - 1) ** 2 / (a ** i)) for i in range(K)]
    xs, acc = simple_parallel_tempering(x, K, N, p, u, u0, Ns)
    xs_walk = random_walk_metropolis(x_walk, N, p[0], u[0], u0)
    r_xs = acf(xs)
    r_walk = acf(xs_walk)

    ax = fig.add_subplot(5, 2, 2*j + 1)
    ax.bar(range(len(r_xs)), r_xs, label='simple_PT')
    ax.set_title('gamma = ' + str(gamma))
    plt.legend()

    ax2 = fig.add_subplot(5, 2, 2*j + 2)
    ax2.bar(range(len(r_walk)), r_walk, label='Walk')
    ax2.set_title('gamma = ' + str(gamma))
    plt.legend()
plt.savefig('figures/project_ex2_auto_correlation.png')
plt.show()

# plot the trace-plots
x = np.zeros((K, N))
fig = plt.figure(figsize=(15, 25))
for j, gamma in enumerate(gammas):
    u = [lambda x, i=i: np.exp(-gamma * (x ** 2 - 1) ** 2 / (a ** i)) for i in range(K)]
    acc = 0
    xs, acc = simple_parallel_tempering(x, K, N, p, u, u0, Ns)
    xs_walk = random_walk_metropolis(x_walk, N, p[0], u[0], u0)

    ax = fig.add_subplot(10, 1, 2*j + 1)
    ax.plot(xs, label='simple_PT')
    ax.set_title('gamma = ' + str(gamma))
    plt.legend()

    ax2 = fig.add_subplot(10, 1, 2*j + 2)
    ax2.plot(xs_walk, label='Walk')
    ax2.set_title('gamma = ' + str(gamma))
    plt.legend()
plt.savefig('figures/project_ex2_trace_plot.png')
plt.show()

# compute the effective sample size
x = np.zeros((K, N))
for j, gamma in enumerate(gammas):
    u = [lambda x, i=i: np.exp(-gamma * (x ** 2 - 1) ** 2 / (a ** i)) for i in range(K)]
    ess_xs = 0
    ess_walk = 0
    for l in range(5):
        xs, acc = simple_parallel_tempering(x, K, N, p, u, u0, Ns)
        xs_walk = random_walk_metropolis(x_walk, N, p[0], u[0], u0)
        ess_xs += np.abs(N/(1+2*(acf(xs, 1000).sum()-1)))
        ess_walk += np.abs(N/(1+2*(acf(xs_walk, 1000).sum()-1)))
    print('effective sample size for Markov chain generated by simple PT: %f' % (ess_xs/5))
    print('effective sample size for Markov chain generated by random walk MH: %f' % (ess_walk/5))

'''
gamma = 1
effective sample size for Markov chain generated by simple PT: 2135.576968
effective sample size for Markov chain generated by random walk MH: 2496.629166

gamma = 2
effective sample size for Markov chain generated by simple PT: 7569.012008
effective sample size for Markov chain generated by random walk MH: 3011.531131

gamma = 4
effective sample size for Markov chain generated by simple PT: 4402.382063
effective sample size for Markov chain generated by random walk MH: 1481.703287

gamma = 8
effective sample size for Markov chain generated by simple PT: 1601.226823
effective sample size for Markov chain generated by random walk MH: 862.148858

gamma = 16
effective sample size for Markov chain generated by simple PT: 8534.720071
effective sample size for Markov chain generated by random walk MH: 388.920264
'''